use anyhow::Result;
use inquire::Select;
use strum::IntoEnumIterator;

#[derive(Debug, Clone, Copy, strum::Display, strum::EnumIter)]
enum Service {
    Amplify,
    APIGateway,
    APIGatewayV2,
    AppFlow,
    AppMesh,
    AppRunner,
    AppSync,
    Athena,
    Batch,
    Bedrock,
    Billing,
    Budgets,
    Chatbot,
    Cloud9,
    CloudFormation,
    CloudFront,
    CloudTrail,
    CloudWatch,
    CodeBuild,
    CodeCatalyst,
    CodeCommit,
    CodeDeploy,
    CodePipeline,
    Comprehend,
    ComprehendMedical,
    ControlTower,
    DataZone,
    DynamoDB,
    EBS,
    EC2,
    ECR,
    ECS,
    EFS,
    EKS,
    ElasticBeanstalk,
    ElasticLoadBalancing,
    ElasticLoadBalancingV2,
    EMR,
    EventBridge,
    EventBridgePipes,
    EventBridgeScheduler,
    Firehose,
    Glue,
    GlueDataBrew,
    GuardDuty,
    IAM,
    IdentityStore,
    IoTGreenGrass,
    IoTGreenGrassV2,
    Lambda,
    QuickSight,
    RAM,
    RDS,
    RedShift,
    RedShiftData,
    RedShiftServerless,
    S3,
    S3Glacier,
    S3Tables,
    SageMaker,
    SecretsManager,
    SES,
    SQS,
    StepFunctions,
    SNS,
    SSO,
    STS,
    UserNotifications,
}

impl Service {
    fn url_expression(&self) -> &str {
        match self {
            Service::Amplify => "amplify",
            Service::APIGateway => "apigateway",
            Service::APIGatewayV2 => "apigatewayv2",
            Service::AppFlow => "appflow",
            Service::AppMesh => "appmesh",
            Service::AppRunner => "apprunner",
            Service::AppSync => "appsync",
            Service::Athena => "athena",
            Service::Batch => "batch",
            Service::Bedrock => "bedrock",
            Service::Billing => "billing",
            Service::Budgets => "budgets",
            Service::Chatbot => "chatbot",
            Service::Cloud9 => "cloud9",
            Service::CloudFormation => "cloudformation",
            Service::CloudFront => "cloudfront",
            Service::CloudTrail => "cloudtrail",
            Service::CloudWatch => "cloudwatch",
            Service::CodeBuild => "codebuild",
            Service::CodeCatalyst => "codecatalyst",
            Service::CodeCommit => "codecommit",
            Service::CodeDeploy => "codedeploy",
            Service::CodePipeline => "codepipeline",
            Service::Comprehend => "comprehend",
            Service::ComprehendMedical => "comprehendmedical",
            Service::ControlTower => "controltower",
            Service::DataZone => "datazone",
            Service::DynamoDB => "dynamodb",
            Service::EBS => "ebs",
            Service::EC2 => "ec2",
            Service::ECR => "ecr",
            Service::ECS => "ecs",
            Service::EFS => "efs",
            Service::EKS => "eks",
            Service::ElasticBeanstalk => "elasticbeanstalk",
            Service::ElasticLoadBalancing => "elasticloadbalancing",
            Service::ElasticLoadBalancingV2 => "elasticloadbalancingv2",
            Service::EMR => "emr",
            Service::EventBridge => "eventbridge",
            Service::EventBridgePipes => "pipes",
            Service::EventBridgeScheduler => "scheduler",
            Service::Firehose => "firehose",
            Service::Glue => "glue",
            Service::GlueDataBrew => "databrew",
            Service::GuardDuty => "guardduty",
            Service::IAM => "iam",
            Service::IdentityStore => "identitystore",
            Service::IoTGreenGrass => "greengrass",
            Service::IoTGreenGrassV2 => "greengrassv2",
            Service::Lambda => "lambda",
            Service::QuickSight => "quicksight",
            Service::RAM => "ram",
            Service::RDS => "rds",
            Service::RedShift => "redshift",
            Service::RedShiftData => "redshiftdata",
            Service::RedShiftServerless => "redshiftserverless",
            Service::S3 => "s3",
            Service::S3Glacier => "glacier",
            Service::S3Tables => "s3tables",
            Service::SageMaker => "sagemaker",
            Service::SecretsManager => "secretsmanager",
            Service::SES => "ses",
            Service::SQS => "sqs",
            Service::StepFunctions => "sfn",
            Service::SNS => "sns",
            Service::SSO => "sso",
            Service::STS => "sts",
            Service::UserNotifications => "notifications",
        }
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let all_services = Service::iter().collect::<Vec<_>>();
    let s = Select::new("abc", all_services).prompt()?;
    let s = s.url_expression();

    let url = format!("https://docs.rs/aws-sdk-{s}/latest/aws_sdk_{s}/client/struct.Client.html");
    open::that(url)?;

    Ok(())
}
